--- 
all: 
  children: 
    calico-rr: 
      hosts: {}
    etcd: 
      hosts: 
        master1: ~
        master2: ~
        master3: ~
    k8s-cluster: 
      children: 
        kube-master: ~
        kube-node: ~
    kube-master: 
      hosts: 
        master1: ~
        master2: ~
        master3: ~
    kube-node: 
      hosts: 
        master1: ~
        master2: ~
        master3: ~
        worker1: ~
        worker2: ~
        worker3: ~
  hosts: 
    master1: 
      access_ip: "172.42.42.11"
      ansible_host: "172.42.42.11"
      ip: "172.42.42.11"
    master2: 
      access_ip: "172.42.42.12"
      ansible_host: "172.42.42.12"
      ip: "172.42.42.12"
    master3: 
      access_ip: "172.42.42.13"
      ansible_host: "172.42.42.13"
      ip: "172.42.42.13"
    worker1: 
      access_ip: "172.42.42.21"
      ansible_host: "172.42.42.21"
      ip: "172.42.42.21"
    worker2: 
      access_ip: "172.42.42.22"
      ansible_host: "172.42.42.22"
      ip: "172.42.42.22"
    worker3: 
      access_ip: "172.42.42.23"
      ansible_host: "172.42.42.23"
      ip: "172.42.42.23"
